version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: nginx
    container_name: frontend
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
